# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cb9d2452f4381d2c42761015ca25c501b02b3121ac8140e163c914bfab40f2d64fa1bb95c0bd27e09c911979123a26bc31d60d993ece44112e09d91a3492038

test:
  secret_key_base: f5e2608a9f568a4e29ba7fa62a7f2e52988449f9ff503aea7143ecf6fc763d84b7534e4df9ec2d7595a6bddf2e7fd4e09a8af4c56a77b571e59b34ccab9910c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
